# SPDX-FileCopyrightText: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.8 on 2026-09-15 19:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import peblate.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [  # noqa: RUF012 - Django migration declaration
        ("trans", "0103_project_public_sharing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012 - Django migration declaration
        migrations.CreateModel(
            name="LanguageJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(max_length=10)),
                ("status", models.CharField(default="queued", max_length=10)),
                (
                    "phase",
                    models.CharField(default="Waiting for a worker", max_length=120),
                ),
                ("locale", models.CharField(blank=True, max_length=80)),
                ("source_revision", models.CharField(blank=True, max_length=64)),
                ("snapshot_at", models.DateTimeField(null=True)),
                ("report", models.JSONField(null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(default=peblate.models.expires_at)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trans.translation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("owner", "translation", "operation"),
                        name="peblate_one_active_job",
                    )
                ],
            },
        ),
    ]
